global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/jino-compare-actuator/prometheus'
    scheme: 'https'
    static_configs:
      - targets: ['allcomparedb-latest.onrender.com']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']     
